default_language_version:
  python: python3

repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        language: python # Указываем Python вместо bash

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language: python
        args: ["--include", "\\.py$|\\.rpy$"]
