default_language_version:
  python: python3

repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        language: python

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language: python
        args: ["--include", "\\.py$|\\.rpy$"]

  - repo: local
    hooks:
      - id: lint-hook
        name: Lint Hook
        entry: cmd /c "hooks\lint.bat"
        language: system
        stages: [commit]

      - id: branch-hook
        name: Branch Hook
        entry: cmd /c "hooks\branch.bat"
        language: system
        stages: [commit]

      - id: branch-hook
        name: Branch name Hook
        entry: cmd /c "hooks\main_commit.bat"
        language: system
        stages: [commit]
