[tool.black]
line-length = 88
include = '\.py$'  # Проверяем только .py файлы
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.venv
  | build
  | dist
  | game/.*\.rpy  # Игнорируем все .rpy файлы в папке game
)/
'''
