#Anon block
define anon = Character("Анон", color="#c8ffc8")
image anon neutral = im.Flip("game\images\anon\anon_neutral.png", horizontal=True)
image anon angry =  im.Flip("game\images\anon\anon_angry.png", horizontal=True)
image anon very angry = im.Flip("game\images\anon\anon_very angry", horizontal=True)
image anon sad = im.Flip("game\images\anon\anon_sad", horizontal=True)
image anon shocked = im.Flip("game\images\anon\anon_shocked", horizontal=Truea)
image anon considering = im.Flip("game\images\anon\anon_considering", horizontal=True)
image anon happy = im.Flip("game\images\anon\anon_happy", horizontal=True)
image anon fear = im.Flip("game\images\anon\anon_fear", horizontal=True)

#Amber block
define amber = Character("Эмбер", color="#cc410e")
image amber neutral = im.Flip("game\images\amber\amber_neutral", horizontal=True)
image amber angry =  im.Flip("game\images\amber\amber_angry", horizontal=True)
image amber very angry = im.Flip("game\images\amber\amber_very angry", horizontal=True)
image amber sad = im.Flip("game\images\amber\amber_sad", horizontal=True)
image amber shocked = im.Flip("game\images\amber\amber_shocked", horizontal=True)
image amber considering = im.Flip("game\images\amber\amber_considering", horizontal=True)
image amber happy = im.Flip("game\images\amber\amber_happy", horizontal=True)
image amber fear = im.Flip("game\images\amber\amber_fear", horizontal=True)

#Lucy block
define lucy = Character("Люси", color="#8edff3")
image lucy neutral = im.Flip("game\images\lucy\lucy_neutral", horizontal=True)
image lucy angry =  im.Flip("game\images\lucy\lucy_angry", horizontal=True)
image lucy very angry = im.Flip("game\images\lucy\lucy_very angry", horizontal=True)
image lucy sad = im.Flip("game\images\lucy\lucy_sad", horizontal=True)
image lucy shocked = im.Flip("game\images\lucy\lucy_shocked", horizontal=True)
image lucy considering = im.Flip("game\images\lucy\lucy_considering", horizontal=True)
image lucy happy = im.Flip("game\images\lucy\lucy_happy", horizontal=True)
image lucy fear = im.Flip("game\images\lucy\lucy_fear", horizontal=True)

#Samantha block
define samantha = Character("Саманта", color="#085669")
image samantha neutral = im.Flip("game\images\samantha\samantha_neutral", horizontal=True)
image samantha angry =  im.Flip("game\images\samantha\samantha_angry", horizontal=True)
image samantha very angry = im.Flip("game\images\samantha\samantha_very angry", horizontal=True)
image samantha sad = im.Flip("game\images\samantha\samantha_sad", horizontal=True)
image samantha shocked = im.Flip("game\images\samantha\samantha_shocked", horizontal=True)
image samantha considering = im.Flip("game\isamantha\amber\samantha_considering", horizontal=True)
image samantha happy = im.Flip("game\images\samantha\samantha_happy", horizontal=True)
image samantha fear = im.Flip("game\images\samantha\samantha_fear", horizontal=True)

#Ripley block
define ripley = Character("Рипли", color="#74310a")
image ripley neutral = im.Flip("game\images\ripley\ripley_neutral", horizontal=True)
image ripley angry =  im.Flip("game\images\ripley\ripley_angry", horizontal=True)
image ripley very angry = im.Flip("game\images\ripley\ripley_very angry", horizontal=True)
image ripley sad = im.Flip("game\images\ripley\ripley_sad", horizontal=True)
image ripley shocked = im.Flip("game\images\ripley\ripley_shocked", horizontal=True)
image ripley considering = im.Flip("game\images\ripley\ripley_considering", horizontal=True)
image ripley happy = im.Flip("game\images\ripley\ripley_happy", horizontal=True)
image ripley fear = im.Flip("game\images\ripley\ripley_fear", horizontal=True)

#Reed block
define reed = Character("Рид", color="#b94c4c")
image reed neutral = im.Flip("game\images\reed\reed_neutral", horizontal=True)
image reed angry =  im.Flip("game\images\reed\reed_angry", horizontal=True)
image reed very angry = im.Flip("game\images\reed\reed_very angry", horizontal=True)
image reed sad = im.Flip("game\images\reed\reed_sad", horizontal=True)
image reed shocked = im.Flip("game\images\reed\reed_shocked", horizontal=True)
image reed considering = im.Flip("game\images\reed\reed_considering", horizontal=True)
image reed happy = im.Flip("game\images\reed\reed_happy", horizontal=True)
image reed fear = im.Flip("game\images\reed\reed_fear", horizontal=True)

#Neser block
define neser = Character("Незер", color="#8edff3")
image neser neutral = im.Flip("game\images\neser\neser_neutral", horizontal=True)
image neser angry =  im.Flip("game\images\neser\neser_angry", horizontal=True)
image neser very angry = im.Flip("game\images\neser\neser_very angry", horizontal=True)
image neser sad = im.Flip("game\images\neser\neser_sad", horizontal=True)
image neser shocked = im.Flip("game\images\neser\neser_shocked", horizontal=True)
image neser considering = im.Flip("game\images\neser\neser_considering", horizontal=True)
image neser happy = im.Flip("game\images\neser\neser_happy", horizontal=True)
image neser fear = im.Flip("game\images\neser\neser_fear", horizontal=True)

#Cynthia block
define cynthia = Character("Синтия", color="#8edff3")
image cynthia neutral = im.Flip("game\images\cynthia\cynthia_neutral", horizontal=True)
image cynthia angry =  im.Flip("game\images\cynthia\cynthia_angry", horizontal=True)
image cynthia very angry = im.Flip("game\images\cynthia\cynthia_very angry", horizontal=True)
image cynthia sad = im.Flip("game\images\cynthia\cynthia_sad", horizontal=True)
image cynthia shocked = im.Flip("game\images\cynthia\cynthia_shocked", horizontal=True)
image cynthia considering = im.Flip("game\images\cynthia\cynthia_considering", horizontal=True)
image cynthia happy = im.Flip("game\images\cynthia\cynthia_happy", horizontal=True)
image cynthia fear = im.Flip("game\images\cynthia\cynthia_fear", horizontal=True)

#Sera block
define sera = Character("Сера", color="#1bb15a")
image sera neutral = im.Flip("game\images\sera\sera_neutral", horizontal=True)
image sera angry =  im.Flip("game\images\sera\sera_angry", horizontal=True)
image sera very angry = im.Flip("game\images\sera\sera_very angry", horizontal=True)
image sera sad = im.Flip("game\images\sera\sera_sad", horizontal=True)
image sera shocked = im.Flip("game\images\sera\sera_shocked", horizontal=True)
image sera considering = im.Flip("game\images\sera\sera_considering", horizontal=True)
image sera happy = im.Flip("game\images\sera\sera_happy", horizontal=True)
image sera fear = im.Flip("game\images\sera\sera_fear", horizontal=True)

#Trish block
define trish = Character("Триш", color="#9512c9")
image trish neutral = im.Flip("game\images\trush\trush_neutral", horizontal=True)
image trish angry =  im.Flip("game\images\trush\trush_angry", horizontal=True)
image trish very angry = im.Flip("game\images\trush\trush_very angry", horizontal=True)
image trish sad = im.Flip("game\images\trush\trush_sad", horizontal=True)
image trish shocked = im.Flip("game\images\trush\trush_shocked", horizontal=True)
image trish considering = im.Flip("game\images\trush\trush_considering", horizontal=True)
image trish happy = im.Flip("game\images\trush\trush_happy", horizontal=True)
image trish fear = im.Flip("game\images\trush\trush_fear", horizontal=True)

#Rosa block
define rosa = Character("Роза", color="#8f5c2d")
image rosa neutral = im.Flip("game\images\rosa\rosa_neutral", horizontal=True)
image rosa angry =  im.Flip("game\images\arosa_angry", horizontal=True)
image rosa very angry = im.Flip("game\images\rosa\rosa_very angry", horizontal=True)
image rosa sad = im.Flip("game\images\rosa\rosa_sad", horizontal=True)
image rosa shocked = im.Flip("game\images\rosa\rosa_shocked", horizontal=True)
image rosa considering = im.Flip("game\images\rosa\rosa_considering", horizontal=True)
image rosa happy = im.Flip("game\images\rosa\rosa_happy", horizontal=True)
image rosa fear = im.Flip("game\images\rosa\rosa_fear", horizontal=True)

#Stella block
define stella = Character("Стелла", color="#29cf74")
image stella neutral = im.Flip("game\images\stella\stella_neutral", horizontal=True)
image stella angry =  im.Flip("game\images\stella\stella_angry", horizontal=True)
image stella very angry = im.Flip("game\images\stella\stella_very angry", horizontal=True)
image stella sad = im.Flip("game\images\amber\stella_sad", horizontal=True)
image stella shocked = im.Flip("game\images\stella\stella_shocked", horizontal=True)
image stella considering = im.Flip("game\images\stella\stella_considering", horizontal=True)
image stella happy = im.Flip("game\images\stella\stella_happy", horizontal=True)
image stella fear = im.Flip("game\images\stella\stella_fear", horizontal=True)

#Anon boss block
define anon_boss = Character("Босс Анона", color="#8f5c2d")
image anon_boss neutral = im.Flip("game\images\anon_boss\anon_boss_neutral", horizontal=True)
image anon_boss angry =  im.Flip("game\images\anon_boss\anon_boss_angry", horizontal=True)
image anon_boss very angry = im.Flip("game\imagesanon_bossr\anon_boss_very angry", horizontal=True)
image anon_boss sad = im.Flip("game\images\anon_boss\anon_boss_sad", horizontal=True)
image anon_boss shocked = im.Flip("game\images\anon_boss\anon_boss_shocked", horizontal=True)
image anon_boss considering = im.Flip("game\images\anon_boss\anon_boss_considering", horizontal=True)
image anon_boss happy = im.Flip("game\images\anon_boss\anon_boss_happy", horizontal=True)
image anon_boss fear = im.Flip("game\images\anon_boss\anon_boss_fear", horizontal=True)