#Anon block
define anon = Character("Анон", color="#c8ffc8")
image anon neutral = im.Flip("", horizontal=True)
image anon angry =  im.Flip("", horizontal=True)
image anon very angry = im.Flip("", horizontal=True)
image anon sad = im.Flip("", horizontal=True)
image anon shocked = im.Flip("", horizontal=True)
image anon considering = im.Flip("", horizontal=True)
image anon happy = im.Flip("", horizontal=True)
image anon fear = im.Flip("", horizontal=True)

#Amber block
define amber = Character("Амбер", color="#cc410e")
image amber neutral = im.Flip("", horizontal=True)
image amber angry =  im.Flip("", horizontal=True)
image amber very angry = im.Flip("", horizontal=True)
image amber sad = im.Flip("", horizontal=True)
image amber shocked = im.Flip("", horizontal=True)
image amber considering = im.Flip("", horizontal=True)
image amber happy = im.Flip("", horizontal=True)
image amber fear = im.Flip("", horizontal=True)

#Lucy block
define lucy = Character("Люси", color="#8edff3")
image lucy neutral = im.Flip("", horizontal=True)
image lucy angry =  im.Flip("", horizontal=True)
image lucy very angry = im.Flip("", horizontal=True)
image lucy sad = im.Flip("", horizontal=True)
image lucy shocked = im.Flip("", horizontal=True)
image lucy considering = im.Flip("", horizontal=True)
image lucy happy = im.Flip("", horizontal=True)
image lucy fear = im.Flip("", horizontal=True)

#Samantha block
define samantha = Character("Саманта", color="#085669")
image samantha neutral = im.Flip("", horizontal=True)
image samantha angry =  im.Flip("", horizontal=True)
image samantha very angry = im.Flip("", horizontal=True)
image samantha sad = im.Flip("", horizontal=True)
image samantha shocked = im.Flip("", horizontal=True)
image samantha considering = im.Flip("", horizontal=True)
image samantha happy = im.Flip("", horizontal=True)
image samantha fear = im.Flip("", horizontal=True)

#Ripley block
define ripley = Character("Рипли", color="#74310a")
image ripley neutral = im.Flip("", horizontal=True)
image ripley angry =  im.Flip("", horizontal=True)
image ripley very angry = im.Flip("", horizontal=True)
image ripley sad = im.Flip("", horizontal=True)
image ripley shocked = im.Flip("", horizontal=True)
image ripley considering = im.Flip("", horizontal=True)
image ripley happy = im.Flip("", horizontal=True)
image ripley fear = im.Flip("", horizontal=True)

#Reed block
define reed = Character("Рид", color="#b94c4c")
image reed neutral = im.Flip("", horizontal=True)
image reed angry =  im.Flip("", horizontal=True)
image reed very angry = im.Flip("", horizontal=True)
image reed sad = im.Flip("", horizontal=True)
image reed shocked = im.Flip("", horizontal=True)
image reed considering = im.Flip("", horizontal=True)
image reed happy = im.Flip("", horizontal=True)
image reed fear = im.Flip("", horizontal=True)

#Neser block
define neser = Character("Незер", color="#8edff3")
image neser neutral = im.Flip("", horizontal=True)
image neser angry =  im.Flip("", horizontal=True)
image neser very angry = im.Flip("", horizontal=True)
image neser sad = im.Flip("", horizontal=True)
image neser shocked = im.Flip("", horizontal=True)
image neser considering = im.Flip("", horizontal=True)
image neser happy = im.Flip("", horizontal=True)
image neser fear = im.Flip("", horizontal=True)

#Cynthia block
define cynthia = Character("Синтия", color="#8edff3")
image cynthia neutral = im.Flip("", horizontal=True)
image cynthia angry =  im.Flip("", horizontal=True)
image cynthia very angry = im.Flip("", horizontal=True)
image cynthia sad = im.Flip("", horizontal=True)
image cynthia shocked = im.Flip("", horizontal=True)
image cynthia considering = im.Flip("", horizontal=True)
image cynthia happy = im.Flip("", horizontal=True)
image cynthia fear = im.Flip("", horizontal=True)

#Sera block
define sera = Character("Сера", color="#1bb15a")
image sera neutral = im.Flip("", horizontal=True)
image sera angry =  im.Flip("", horizontal=True)
image sera very angry = im.Flip("", horizontal=True)
image sera sad = im.Flip("", horizontal=True)
image sera shocked = im.Flip("", horizontal=True)
image sera considering = im.Flip("", horizontal=True)
image sera happy = im.Flip("", horizontal=True)
image sera fear = im.Flip("", horizontal=True)

#Trish block
define trish = Character("Триш", color="#9512c9")
image trish neutral = im.Flip("", horizontal=True)
image trish angry =  im.Flip("", horizontal=True)
image trish very angry = im.Flip("", horizontal=True)
image trish sad = im.Flip("", horizontal=True)
image trish shocked = im.Flip("", horizontal=True)
image trish considering = im.Flip("", horizontal=True)
image trish happy = im.Flip("", horizontal=True)
image trish fear = im.Flip("", horizontal=True)

#Rosa block
define rosa = Character("Роза", color="#8f5c2d")
image rosa neutral = im.Flip("", horizontal=True)
image rosa angry =  im.Flip("", horizontal=True)
image rosa very angry = im.Flip("", horizontal=True)
image rosa sad = im.Flip("", horizontal=True)
image rosa shocked = im.Flip("", horizontal=True)
image rosa considering = im.Flip("", horizontal=True)
image rosa happy = im.Flip("", horizontal=True)
image rosa fear = im.Flip("", horizontal=True)

#Stella block
define stella = Character("Стелла", color="#29cf74")
image stella neutral = im.Flip("", horizontal=True)
image stella angry =  im.Flip("", horizontal=True)
image stella very angry = im.Flip("", horizontal=True)
image stella sad = im.Flip("", horizontal=True)
image stella shocked = im.Flip("", horizontal=True)
image stella considering = im.Flip("", horizontal=True)
image stella happy = im.Flip("", horizontal=True)
image stella fear = im.Flip("", horizontal=True)

#Anon boss block
define anon_boss = Character("Босс Анона", color="#8f5c2d")
image anon_boss neutral = im.Flip("", horizontal=True)
image anon_boss angry =  im.Flip("", horizontal=True)
image anon_boss very angry = im.Flip("", horizontal=True)
image anon_boss sad = im.Flip("", horizontal=True)
image anon_boss shocked = im.Flip("", horizontal=True)
image anon_boss considering = im.Flip("", horizontal=True)
image anon_boss happy = im.Flip("", horizontal=True)
image anon_boss fear = im.Flip("", horizontal=True)