#music
define m_intro            = ""
define m_lofi_kitchen     = ""
define m_evening          = ""
define m_party            = ""
define m_nostalgy         = ""
define m_shop             = ""

#SFX
define s_sizzle           = ""
define s_compressor       = ""
define s_fall             = ""
define s_crash            = ""
define s_door_open        = ""
define s_door_close       = ""
define s_steps_wood       = ""
define s_skate            = ""
define s_confetti         = ""
define s_ringtone         = ""
define s_phone_call       = ""
define s_sms              = ""
define s_tv_on            = ""
define s_tv_off           = ""
define s_magazine         = ""
define s_can_hit          = ""
define s_water_pour       = ""
define s_sneeze           = ""
define s_knock            = ""
define s_wood_creak       = ""
define s_flash            = ""
define s_can_kick         = ""
define s_can_drop         = ""
define s_basketball       = ""
define s_street_sounds    = ""
define s_door_bell        = ""